
begin;

create table if not exists public.work_items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (length(title) between 1 and 500),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists work_items_owner_id_idx
  on public.work_items(owner_id);

alter table public.work_items enable row level security;

create policy "owners can read work items"
  on public.work_items for select to authenticated
  using ((select auth.uid()) = owner_id);

create policy "owners can insert work items"
  on public.work_items for insert to authenticated
  with check ((select auth.uid()) = owner_id);

create policy "owners can update work items"
  on public.work_items for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

create policy "owners can delete work items"
  on public.work_items for delete to authenticated
  using ((select auth.uid()) = owner_id);

commit;
