'use strict';

const { CONTRACTS } = require('./webviewMessages');

const UI_ONLY = Object.freeze({
  closeModal: ['modal', 'close dialog and restore focus'], commandCenter: ['modal', 'open command center'],
  inspectMetric: ['inspection', 'open the exact metric label, value, detail, and active-surface context'],
  newParallelPlan: ['modal', 'open validated parallel-plan form'], capabilityTab: ['view-state', 'select capability catalog'],
  surfaceScope: ['view-state', 'select surface scope and persist view state'], informationTab: ['view-state', 'select human or machine record view'],
  graphLayout: ['graph-state', 'select deterministic community, flow, or orbit layout'], graphToggleInspector: ['graph-state', 'toggle relationship inspector'],
  graphFocus: ['graph-state', 'enter or leave full-screen graph focus'], graphBack: ['graph-state', 'restore prior selected graph node'],
  graphZoomIn: ['graph-state', 'increase bounded graph scale'], graphZoomOut: ['graph-state', 'decrease bounded graph scale'],
  graphFit: ['graph-state', 'fit graph to visible viewport'], graphReset: ['graph-state', 'reset graph transform'],
  graphDepth: ['graph-state', 'expand or contract the bounded graph neighborhood'],
  selectGraphNode: ['graph-state', 'select one already-loaded record without issuing another host query'],
  inspectGraphRecord: ['inspection', 'open source identity and provenance from the current bounded graph page'],
  knowledgePropose: ['modal', 'open a source- and evidence-bound knowledge proposal form'],
  knowledgeReject: ['modal', 'open an evidence-backed knowledge rejection form'],
  learningObserve: ['modal', 'open immutable operation-evidence capture'],
  learningAppendEvidence: ['modal', 'append evidence within the pipeline source boundary'],
  learningPattern: ['modal', 'open hashless aggregation and pattern extraction inputs'],
  learningHypothesis: ['modal', 'open immutable incumbent/challenger revision inputs'],
  learningTrial: ['modal', 'open one evidence-bound A/B trial input'],
  learningResearch: ['modal', 'open independent research and optional tier-three inputs'],
  learningFinalValidation: ['modal', 'open final evidence and partial-unit validation inputs'],
  learningReuse: ['modal', 'open cumulative measured-reuse inputs'],
  inspectLearningPipeline: ['inspection', 'open the signed learning pipeline and gate evidence'],
  openStudioDraft: ['modal', 'open a structured versioned studio draft editor'],
  resumeWorkingStudioDraft: ['draft-state', 'resume one bounded webview-local unsaved draft without host authority or persistence outside VS Code view state'],
  discardWorkingStudioDraft: ['draft-state', 'explicitly discard one retained webview-local unsaved draft and open a clean editor'],
  openStudioFromCatalog: ['modal', 'open a supported existing agent or workflow record as a new immutable Studio revision'],
  importCatalogDefinition: ['draft-state', 'adapt one external agent or workflow definition into an independent editable Studio candidate without predecessor lineage or inherited authority'],
  agentAddTopologyNode: ['draft-state', 'add one optional typed AgentSpec node to the unsaved visual candidate'],
  agentRemoveTopologyNode: ['draft-state', 'remove one optional typed AgentSpec node from the unsaved visual candidate'],
  acceptStudioVersionSuggestion: ['draft-state', 'apply the request-bound host allocation suggestion to the unsaved candidate without saving it'],
  operateStudioRevision: ['modal', 'resume one exact durable Studio candidate lifecycle or load one authenticated admitted revision without changing its version'],
  studioEditorTab: ['view-state', 'switch synchronized visual and canonical Studio views'],
  agentSelectNode: ['editor-state', 'select one closed AgentSpec graph node and open its field-linked inspector'],
  agentPortConnect: ['editor-state', 'start or complete one admitted typed AgentSpec connection in the unsaved working graph'],
  agentCancelConnection: ['editor-state', 'cancel the pending AgentSpec connection without changing the unsaved working graph'],
  agentRemoveEdge: ['editor-state', 'remove one typed AgentSpec connection from the unsaved working graph'],
  agentZoom: ['view-state', 'change the bounded Agent Studio canvas scale without changing the candidate'],
  agentFit: ['view-state', 'fit the complete AgentSpec graph into the current canvas'],
  agentAutoLayout: ['editor-state', 'apply deterministic bounded coordinates to every AgentSpec graph node'],
  studioApplyJson: ['editor-state', 'validate and apply canonical JSON to the typed agent or workflow editor'],
  forkStudioCandidate: ['draft-state', 'copy predecessor content into an independent unbound 1.0.0 candidate with no inherited allocation or authority'],
  agentAddBinding: ['editor-state', 'add a px-standard capability binding declaration to the agent candidate'],
  agentRemoveBinding: ['editor-state', 'remove a capability binding declaration and its agent reference'],
  agentAddGrant: ['editor-state', 'add a bounded effect-grant declaration to the agent candidate'],
  agentRemoveGrant: ['editor-state', 'remove an effect-grant declaration and linked candidate references'],
  workflowAddNode: ['editor-state', 'add a typed node by palette activation or drag and drop'],
  workflowSelectNode: ['editor-state', 'select a workflow node for guided editing'],
  workflowAddPort: ['editor-state', 'add a typed input or output port to the selected node'],
  workflowRemovePort: ['editor-state', 'remove a typed port and any connected draft edges'],
  workflowMoveNode: ['editor-state', 'reorder the selected workflow node with keyboard-equivalent controls'],
  workflowRemoveNode: ['editor-state', 'remove a node and its connected draft edges'],
  workflowConnectNodes: ['editor-state', 'add a typed draft edge between selected nodes'],
  workflowPortConnect: ['editor-state', 'start or complete a type-checked direct port connection'],
  workflowCancelConnection: ['editor-state', 'cancel the pending direct port connection'],
  workflowAutoLayout: ['editor-state', 'apply deterministic dependency-layer layout to the draft graph'],
  workflowFit: ['view-state', 'fit the workflow draft graph to the visible canvas'],
  workflowZoom: ['view-state', 'change bounded workflow canvas scale'],
  workflowRemoveEdge: ['editor-state', 'remove one selected draft edge'],
  workflowAddBinding: ['editor-state', 'add a workflow capability binding to the in-memory draft'],
  workflowRemoveBinding: ['editor-state', 'remove a workflow binding and its draft references'],
  workflowAddGrant: ['editor-state', 'add a bounded workflow effect grant to the in-memory draft'],
  workflowRemoveGrant: ['editor-state', 'remove a workflow grant and its draft references'],
  skillSelectFile: ['editor-state', 'select a skill package file for text editing'],
  skillAddFile: ['editor-state', 'add a bounded contract, test, or resource file'],
  skillRemoveFile: ['editor-state', 'remove a non-required skill package draft file'],
  graphSaveView: ['modal', 'open the local graph-view preset form'],
  submitGraphSavedView: ['view-state', 'save bounded graph query and layout metadata locally'],
  graphApplySavedView: ['view-state', 'apply a saved graph query, filter, depth, and layout'],
  graphDeleteSavedView: ['view-state', 'remove one local saved graph view'],
  inspectCatalogItem: ['inspection', 'open human and machine-readable catalog record'], inspectReadiness: ['inspection', 'open readiness dimension evidence'],
  compareSkillOriginal: ['inspection', 'compare one verified PX-native package tree and metadata record to its immutable preserved original'],
  inspectProjectMapRecord: ['inspection', 'open one bounded record from the current sealed project-map projection'],
  openProjectModuleMap: ['view-state', 'open the bounded repository explorer with exact file-node and import-edge filters'],
  inspectRuntimeRecord: ['inspection', 'open one bounded runtime work, placement, producer, or provider record'],
  inspectDiagnosticRecord: ['inspection', 'open one current cause, owner, evidence, and post-repair verification trace'],
  knowledgeRollback: ['modal', 'open an evidence-bound knowledge rollback form without mutating state'],
  skillSemanticQuery: ['modal', 'open the domain-separated semantic skill query'],
  inspectReadinessReport: ['inspection', 'open human and machine-readable readiness report'], inspectSensor: ['inspection', 'open current sensor evidence'],
  inspectMachineManifest: ['inspection', 'open AI capability manifest'], claimTask: ['modal', 'open claim form'],
  taskProgress: ['modal', 'open progress receipt form'], completeTask: ['modal', 'open completion receipt form'],
  reconcileTask: ['modal', 'open reconciliation form'], releaseTask: ['modal', 'open task-bound release confirmation and reason form'], captureMemory: ['modal', 'open proposed-memory form'],
  inspectActivityEvent: ['inspection', 'open metadata-only activity record'], inspectMemoryRecord: ['inspection', 'open canonical memory record'],
  environmentScope: ['view-state', 'select environment inventory scope'], inspectEnvironmentRecord: ['inspection', 'open environment record and governed lifecycle options'],
  cleanupSelectAll: ['selection', 'select or clear admitted cleanup candidates'],
  toggleAdvanced: ['view-state', 'toggle admitted advanced surfaces'],
});

const HOST = Object.freeze({
  setupStudio: ['setupStudio', 'workspace-write-and-owned-process', 'authenticated Pacify-X Studio controller + one explicit host confirmation', 'studioSetupResult or operationError', 'admitted starter agent/workflow revisions plus bounded successful run receipts'],
  submitSkillQuery: ['skillQuery', 'read', 'PX-native bounded skill broker', 'skillQueryResult or operationError', 'at most three eligible metadata candidates with selection rationale'],
  hydrateSkillCandidate: ['skillHydrate', 'read', 'PX-native exact-ID skill hydrator', 'skillHydrateResult or operationError', 'exactly one selected admitted skill body'],
  submitParallelPlan: ['createParallelPlan', 'workspace-write', 'coordination controller', 'coordinationResult', 'hash-linked coordination receipt'],
  catalogPrevious: ['catalogQuery', 'read', 'runtime.dashboard_api', 'catalogResult', 'paged response'],
  catalogNext: ['catalogQuery', 'read', 'runtime.dashboard_api', 'catalogResult', 'paged response'],
  catalogRetry: ['catalogQuery', 'read', 'runtime.dashboard_api', 'catalogResult or operationError', 'bounded retry response'],
  graphView: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'bounded graph response'],
  openRepositoryGraph: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'first bounded repository record page with progressive full-map coverage'],
  graphOverview: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'first bounded full-map record page with explicit source and eligible denominators'],
  graphLoadMore: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'next bounded record and relationship pages with explicit coverage'],
  graphLoadAll: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'all remaining bounded record and relationship pages accumulated with explicit coverage'],
  graphCommunity: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'server-filtered community record page'],
  graphClearCommunity: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'unfiltered progressive record page'],
  graphOpenNeighborhood: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'bounded selected-record relationship neighborhood'],
  runGraphSearch: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'bounded graph response'],
  buildRepositoryGraph: ['buildRepositoryGraph', 'workspace-write', 'runtime.project_intelligence', 'graphBuildResult or operationError', 'current project-map build receipt'],
  focusGraphNode: ['graphQuery', 'read', 'runtime.dashboard_api', 'graphResult', 'bounded graph response'],
  exportRecordJson: ['exportRecordJson', 'workspace-write', 'VS Code save-dialog authority', 'host save dialog or operationError', 'filesystem write completion'],
  openExtensionsView: ['openExtensionsView', 'host-ui', 'VS Code command authority', 'host view opens or operationError', 'host acknowledgement'],
  submitClaimTask: ['claimCoordinationTask', 'workspace-write', 'coordination controller', 'coordinationResult', 'lease receipt'],
  renewClaim: ['renewCoordinationClaim', 'workspace-write', 'coordination controller', 'coordinationResult', 'lease renewal receipt'],
  submitTaskProgress: ['recordTaskProgress', 'workspace-write', 'coordination controller', 'coordinationResult', 'progress receipt'],
  submitReconcile: ['reconcileCoordinationTask', 'workspace-write', 'coordination controller', 'coordinationResult', 'reconciliation receipt'],
  submitReleaseTask: ['releaseCoordinationTask', 'workspace-write', 'explicit dashboard confirmation + coordination controller', 'request-bound coordinationResult or operationError', 'reason-hash-bound release authorization and durable receipt'],
  copyTaskHandoff: ['copyTaskHandoff', 'clipboard-write', 'VS Code clipboard authority', 'information message or operationError', 'host acknowledgement'],
  submitMemory: ['captureCoordinationMemory', 'workspace-write', 'coordination controller', 'coordinationResult', 'sealed non-canonical memory receipt'],
  memoryRefresh: ['memoryQuery', 'read', 'canonical workspace memory vault', 'memoryResult', 'lease-bound integrity-checked bounded response'],
  memoryPrevious: ['memoryQuery', 'read', 'canonical workspace memory vault', 'memoryResult', 'previous bounded page'],
  memoryNext: ['memoryQuery', 'read', 'canonical workspace memory vault', 'memoryResult', 'next bounded page'],
  openMemorySource: ['openFile', 'host-ui', 'VS Code document authority + workspace boundary', 'document or operationError', 'path-boundary acknowledgement'],
  configureCanonicalMemory: ['configureCanonicalMemory', 'configuration-write', 'workspace manager + VS Code configuration', 'folder selection, explicit initialization approval, and refreshed snapshot', 'workspace initialization receipt when created'],
  disconnectCanonicalMemory: ['disconnectCanonicalMemory', 'configuration-write', 'VS Code workspace configuration + canonical memory attachment boundary', 'explicit detach approval, refreshed detached snapshot, and no file deletion', 'typed host action receipt with prior and restored workspace root'],
  submitStudioDraft: ['createStudioDraft', 'workspace-write', 'versioned Pacify-X studio controller', 'studioDraftResult or operationError', 'immutable candidate revision receipt'],
  loadSkillPackageEditor: ['loadSkillPackageEditor', 'read', 'PX canonical/preserved skill roots with no-follow boundary', 'skillPackageEditorResult or operationError', 'bounded tree digest and file count'],
  studioLifecycle: ['studioOperation', 'workspace-write-or-owned-process', 'authenticated Pacify-X studio lifecycle controller + retained host authority', 'studioOperationResult or operationError', 'signed lifecycle or run receipt'],
  submitStudioAgentRun: ['studioOperation', 'owned-process', 'authenticated Pacify-X studio lifecycle controller + retained host authority', 'studioOperationResult or operationError', 'objective-bound run receipt'],
  submitStudioWorkflowRun: ['studioOperation', 'owned-process', 'authenticated Pacify-X studio lifecycle controller + retained host authority', 'studioOperationResult or operationError', 'ephemeral-input-bound workflow run receipt'],
  refreshHostModels: ['listHostModels', 'read', 'VS Code Language Model API metadata', 'hostModelCatalog or operationError', 'current host-visible model metadata'],
  openStudioRuns: ['studioOperation', 'read', 'authenticated durable Studio run controller', 'studioOperationResult or operationError', 'authenticated durable run heads'],
  studioRunAction: ['studioOperation', 'owned-process-control', 'authenticated durable Studio run controller + retained host approval', 'studioOperationResult or operationError', 'signed lifecycle transition or status'],
  activityRefresh: ['activityQuery', 'read', 'activity ledger reader', 'activityResult', 'bounded response'],
  reconcileStaleActivity: ['reconcileStaleActivity', 'workspace-write', 'activity ledger controller + explicit host-modal approval', 'activityReconciliationResult, hostActionResult, or operationError', 'request-bound cancellation/no-op or append-only sealed terminal reconciliation receipt'],
  activityPause: ['setActivityPaused', 'configuration-write', 'VS Code workspace configuration', 'configuration change and refreshed snapshot', 'configuration + activity observation'],
  filterActivityCorrelation: ['activityQuery', 'read', 'activity ledger reader', 'activityResult', 'bounded response'],
  cleanupManager: ['scanCleanup', 'read', 'cleanup controller', 'cleanupCandidates or cleanupError', 'classified inventory'],
  refreshCleanup: ['scanCleanup', 'read', 'cleanup controller', 'cleanupCandidates or cleanupError', 'classified inventory'],
  cleanupRecycle: ['executeCleanup', 'filesystem-write', 'cleanup controller', 'cleanupResult or cleanupError', 'verified cleanup receipt'],
  cleanupPermanent: ['executeCleanup', 'destructive-filesystem', 'cleanup controller + explicit modal approval', 'cleanupResult or cleanupError', 'verified cleanup receipt'],
  teamPackPreview: ['teamPackPreview', 'workspace-write', 'team fabric controller', 'teamPackResult', 'preview/staging receipt'],
  enterprisePackToggle: ['enterprisePackToggle', 'workspace-write', 'enterprise state controller', 'enterpriseResult', 'enterprise event receipt'],
  enterpriseTargetConfigure: ['enterpriseTargetConfigure', 'host-ui', 'enterprise state controller', 'enterpriseResult', 'configuration handoff'],
  enterpriseDoctor: ['enterpriseDoctor', 'read', 'enterprise state controller', 'enterpriseResult', 'doctor report'],
  toggleBillablePolicy: ['toggleBillablePolicy', 'configuration-write', 'enterprise policy controller', 'enterpriseResult', 'policy event receipt'],
  refreshEnvironment: ['refreshEnvironment', 'read', 'environment discovery controller', 'environmentInventory or operationError', 'generation + content hash'],
  environmentExtensionDetail: ['environmentExtensionDetail', 'read', 'environment discovery reader', 'environmentExtensionDetail or operationError', 'bounded response'],
  previewExtensionInstall: ['extensionLifecyclePreview', 'read', 'exact extension lifecycle controller + current VS Code inventory', 'extensionLifecyclePreview or operationError', 'request-bound exact install preview token'],
  executeExtensionInstall: ['extensionLifecycleExecute', 'host-extension-write', 'explicit native modal + VS Code extension command authority', 'extensionLifecycleResult or operationError', 'exact installed-identity reconciliation receipt'],
  previewExtensionUpdate: ['extensionUpdatePreview', 'read', 'exact extension lifecycle controller + current VS Code inventory', 'extensionUpdatePreview or operationError', 'request-bound update preview with retained prior identity'],
  executeExtensionUpdate: ['extensionUpdateExecute', 'host-extension-write', 'explicit native modal + VS Code extension command authority', 'extensionUpdateResult or operationError', 'exact observed-version reconciliation receipt'],
  previewExtensionEnablement: ['extensionEnablementPreview', 'read', 'exact extension lifecycle controller + current VS Code inventory', 'extensionEnablementPreview or operationError', 'request-bound scoped native handoff preview'],
  executeExtensionEnablement: ['extensionEnablementExecute', 'host-ui', 'explicit native modal + VS Code extension manager authority', 'extensionEnablementResult or operationError', 'exact native-record handoff receipt without false mutation claim'],
  previewExtensionUninstall: ['extensionUninstallPreview', 'read', 'exact extension lifecycle controller + dependency analyzer', 'extensionUninstallPreview or operationError', 'request-bound consumer-impact preview with retained rollback identity'],
  executeExtensionUninstall: ['extensionUninstallExecute', 'host-extension-write', 'explicit native modal + VS Code extension command authority', 'extensionUninstallResult or operationError', 'absence reconciliation receipt with durable rollback custody'],
  previewExtensionRollback: ['extensionRollbackPreview', 'read', 'durable rollback-identity custody + current VS Code inventory', 'extensionRollbackPreview or operationError', 'request-bound exact retained-version preview'],
  executeExtensionRollback: ['extensionRollbackExecute', 'host-extension-write', 'explicit native modal + VS Code extension command authority', 'extensionRollbackResult or operationError', 'exact restored-version receipt before custody consumption'],
  queryExtensionConflicts: ['extensionConflictQuery', 'read', 'bounded live extension-manifest conflict analyzer', 'extensionConflictResult or operationError', 'typed stable conflict signals with exact participants'],
  previewExtensionConflictResolution: ['extensionConflictResolutionPreview', 'read', 'conflict analyzer + governed lifecycle router', 'extensionConflictResolutionPreview or operationError', 'stale-revalidated exact signal/target/route token'],
  executeExtensionConflictResolution: ['extensionConflictResolutionExecute', 'host-ui-or-routed-preview', 'explicit native modal + governed lifecycle router; downstream mutations retain separate approval', 'extensionConflictResolutionResult or operationError', 'route acknowledgement without false resolved-state claim'],
  previewEnvironmentLifecycle: ['environmentLifecyclePreview', 'read', 'environment lifecycle controller', 'environmentLifecyclePreview or operationError', 'two-snapshot preview token'],
  executeEnvironmentLifecycle: ['environmentLifecycleExecute', 'filesystem-write', 'environment lifecycle controller', 'environmentLifecycleResult or operationError', 'reversible disposition receipt'],
  copyModal: ['copyText', 'clipboard-write', 'VS Code clipboard authority', 'information message or operationError', 'host acknowledgement'],
  refresh: ['refresh', 'read', 'runtime.dashboard_api', 'snapshot or operationError', 'versioned snapshot'],
  openSettings: ['openSettings', 'host-ui', 'VS Code command authority', 'host settings UI or operationError', 'host acknowledgement'],
  validate: ['validate', 'process', 'Pacify-X validation CLI', 'validation or operationError', 'validation result'],
  contextSnapshot: ['createContextSnapshot', 'host-ui', 'context bridge', 'JSON document or operationError', 'host acknowledgement'],
  continueCodex: ['continueCodex', 'host-ui', 'current Codex host + PX context broker', 'JSON context package receipt and explicit authority-boundary message or operationError', 'host handoff acknowledgement and non-execution boundary disposition'],
  cancelCodex: ['cancelCodex', 'host-ui', 'current Codex host', 'host-operation result message with boundary detail', 'non-execution acknowledgement'],
  openCoordinationHandoff: ['openCoordinationHandoff', 'host-ui', 'coordination controller + VS Code document', 'document or operationError', 'host acknowledgement'],
  openEngineRoot: ['openFile', 'host-ui', 'VS Code document authority', 'document, warning, or operationError', 'path-boundary acknowledgement'],
  openKnowledgeSource: ['openFile', 'host-ui', 'VS Code document authority', 'document or operationError', 'path-boundary acknowledgement'],
  inspectPunchCard: ['operationalCardQuery', 'read', 'append-only operational gap ledger', 'operationalCardResult or operationError', 'exact canonical card and complete history'],
  queryOperationalCards: ['operationalCardsQuery', 'read', 'append-only operational gap ledger', 'operationalCardsResult or operationError', 'bounded filtered page with full-ledger denominators'],
  operationalCardsPrevious: ['operationalCardsQuery', 'read', 'append-only operational gap ledger', 'operationalCardsResult or operationError', 'previous bounded card page'],
  operationalCardsNext: ['operationalCardsQuery', 'read', 'append-only operational gap ledger', 'operationalCardsResult or operationError', 'next bounded card page'],
  inspectOperationalInventory: ['operationalInventoryQuery', 'read', 'append-only operational gap ledger', 'operationalInventoryResult or operationError', 'surface/control disposition inventory'],
  openPunchSource: ['openFile', 'host-ui', 'VS Code document authority + engine-root boundary', 'document or operationError', 'path-boundary acknowledgement'],
  knowledgeRefresh: ['studioOperation', 'read', 'authenticated Pacify-X knowledge controller', 'studioOperationResult or operationError', 'bounded knowledge controller snapshot'],
  submitKnowledgeProposal: ['studioOperation', 'workspace-write', 'authenticated Pacify-X knowledge controller + retained host authority', 'studioOperationResult or operationError', 'immutable candidate revision receipt'],
  knowledgeTransition: ['studioOperation', 'workspace-write', 'authenticated Pacify-X knowledge controller + retained host approval', 'studioOperationResult or operationError', 'verified, approved, or promoted lifecycle receipt'],
  submitKnowledgeReject: ['studioOperation', 'workspace-write', 'authenticated Pacify-X knowledge controller + retained host authority', 'studioOperationResult or operationError', 'terminal rejection receipt'],
  submitKnowledgeRollback: ['studioOperation', 'workspace-write', 'authenticated Pacify-X knowledge controller + retained host authority', 'studioOperationResult or operationError', 'signed immutable rollback receipt'],
  knowledgeRecover: ['studioOperation', 'workspace-write', 'authenticated Pacify-X knowledge controller + retained host authority', 'studioOperationResult or operationError', 'signed knowledge and learning projection recovery receipt'],
  submitLearningObservation: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'signed operation-evidence pipeline revision'],
  submitLearningPattern: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'hashless aggregation plus hashed pattern revision'],
  submitLearningHypothesis: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'tier-one/tier-two immutable revision receipt'],
  submitLearningTrial: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'evidence-bound A/B comparison and confidence receipt'],
  submitLearningResearch: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'independent research or tier-three revision receipt'],
  submitLearningFinalValidation: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'dependency-current final promotion decision'],
  learningAdmit: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning and knowledge controllers + retained host authority', 'studioOperationResult or operationError', 'linked non-canonical knowledge proposal receipt'],
  submitLearningReuse: ['studioOperation', 'workspace-write', 'authenticated Pacify-X learning controller + retained host authority', 'studioOperationResult or operationError', 'measured reuse and non-destructive decay decision']
});

function buildUiActionInventory() {
  const inventory = {};
  for (const [action, [state, behavior]] of Object.entries(UI_ONLY)) inventory[action] = {
    action, mode: 'ui-only', inbound_schema: null, authority: 'webview presentation state', effect: 'none-outside-webview',
    state_transition: state, acknowledgement: 'immediate visible UI state', receipt: null, behavior
  };
  for (const [action, [message, effect, authority, acknowledgement, receipt]] of Object.entries(HOST)) {
    if (!Object.hasOwn(CONTRACTS, message)) throw new Error(`ui-action-unknown-message:${action}:${message}`);
    inventory[action] = { action, mode: 'host', inbound_schema: { type: message, fields: CONTRACTS[message] }, authority, effect, state_transition: acknowledgement, acknowledgement, receipt };
  }
  return Object.freeze(inventory);
}

module.exports = { HOST, UI_ONLY, buildUiActionInventory };
