
begin;
create extension if not exists vector;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  source_id text not null,
  chunk_index integer not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding_model text not null,
  embedding vector(1536) not null,
  content_sha256 text not null,
  created_at timestamptz not null default now(),
  unique (tenant_id, source_id, chunk_index, embedding_model)
);

create index if not exists documents_tenant_source_idx
  on public.documents (tenant_id, source_id);

alter table public.documents enable row level security;

create or replace function public.match_documents(
  query_embedding vector(1536),
  match_count integer default 10,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  source_id text,
  chunk_index integer,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
set search_path = ''
as $$
  select
    d.id, d.source_id, d.chunk_index, d.content, d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.documents d
  where d.metadata @> filter
  order by d.embedding <=> query_embedding
  limit greatest(1, least(match_count, 100));
$$;

commit;
