"""Bounded pre-candidate hygiene, quarantine, and readiness evidence.

This owner deliberately distinguishes product state, retained evidence, reusable
tool custody, and disposable certification state.  It never deletes data.
Hard deletion of a validated quarantine remains a separate, explicitly
authorized host operation.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any, Iterable
from uuid import uuid4


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


SCHEMA = "px.pre-candidate-hygiene/1.0"
MANIFEST_SCHEMA = "px.pre-candidate-quarantine/1.0"
REPORT_JSON = Path("evidence/release/pre-candidate-hygiene-report.json")
REPORT_MD = Path("evidence/release/pre-candidate-hygiene-report.md")
QUARANTINE_VALIDATION_JSON = Path(
    "evidence/release/pre-candidate-quarantine-validation.json"
)
QUARANTINE_ROOT = Path(".quarantine")

STATIC_TRANSIENTS: tuple[tuple[str, str, str, str], ...] = (
    (
        "__pycache__",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "python-bytecode-cache-owner",
        "Repository-root Python bytecode cache; regenerated from authoritative source.",
    ),
    (
        "runtime/__pycache__",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "python-bytecode-cache-owner",
        "Runtime Python bytecode cache; regenerated from authoritative source.",
    ),
    (
        "scripts/__pycache__",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "python-bytecode-cache-owner",
        "Script Python bytecode cache; regenerated from authoritative source.",
    ),
    (
        "tests/__pycache__",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "python-bytecode-cache-owner",
        "Test Python bytecode cache; regenerated from authoritative source.",
    ),
    (
        ".engineering-bootstrap/focused-temp",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "focused-test-owner",
        "Excluded focused-test basetemps and their test-created reparse points.",
    ),
    (
        ".engineering-bootstrap/.project-map.staging",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "project-map-staging-owner",
        "Abandoned empty project-map staging root; authoritative map state is elsewhere.",
    ),
    (
        ".pytest_cache",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "pytest",
        "Repository-root pytest tool cache; Git-ignored and outside product custody.",
    ),
    (
        ".engineering-bootstrap/runtime-core/cache",
        "REGENERABLE_DERIVED_STATE",
        "runtime-core-cache-owner",
        "Content-addressed runtime cache regenerated from authoritative inputs.",
    ),
    (
        ".engineering-bootstrap/runtime-core/release-preflight-cache",
        "REGENERABLE_DERIVED_STATE",
        "release-preflight-cache-owner",
        "Release-preflight scratch cache regenerated by its owner.",
    ),
    (
        "temp",
        "DISPOSABLE_CERTIFICATION_TRANSIENT",
        "legacy-temp-owner",
        "Empty Git-ignored legacy transient root.",
    ),
)

PRESERVED_EXTERNAL_PREFIXES = (
    "pacify-x-vscode-test-cache",
    "pacify-x-release-wheelhouse-",
    "pacify-x-release-artifacts-",
    "pacify-x-release-quarantine",
    "pacify-x-recovery-quarantine-",
)

PRESERVED_REPARSE_ROOTS = (
    Path(".engineering-bootstrap/coordination/activity/quarantine"),
    Path(".engineering-bootstrap/diagnostics"),
    Path(".engineering-bootstrap/quarantine"),
    Path(".engineering-bootstrap/test-evidence/adversarial-repair-gates"),
)


class HygieneError(RuntimeError):
    """The bounded hygiene contract was not satisfied."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _atomic_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.{uuid4().hex}.new")
    with temporary.open("x", encoding="utf-8", newline="\n") as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def _lexists(path: Path) -> bool:
    return os.path.lexists(path)


def _inside(path: Path, parent: Path) -> bool:
    try:
        path.resolve(strict=False).relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def _is_preserved_evidence_reparse(root: Path, path: Path) -> bool:
    """Return true only for reparse points confined to declared evidence custody."""
    return any(_inside(path, root / relative) for relative in PRESERVED_REPARSE_ROOTS)


def _terminal_predecessor_intentionally_stale(
    lineage_valid: bool,
    stale_receipts: Iterable[dict[str, Any]],
    *,
    identity_key: str = "group",
) -> bool:
    """Allow intact receipts to remain stale for one exact failed predecessor."""
    rows = list(stale_receipts)
    return bool(lineage_valid and rows) and all(
        isinstance(row.get(identity_key), str)
        and bool(row.get(identity_key))
        and isinstance(row.get("passed"), bool)
        and isinstance(row.get("fresh"), bool)
        and row.get("current") is False
        for row in rows
    )


def _source_invalid_active_predecessor(
    release: dict[str, Any],
    source_release: dict[str, Any],
    predecessor_campaign_id: str,
) -> bool:
    """Mirror the archive owner's exact retained-pass predecessor boundary."""

    from runtime.release_campaign import STAGES

    if (
        release.get("valid") is not True
        or release.get("campaign_id") != predecessor_campaign_id
        or release.get("state") != "active"
        or release.get("apply_count") != 1
        or not isinstance(release.get("identity"), dict)
        or release.get("active_claim") is not None
        or source_release.get("valid") is not False
        or not source_release.get("errors")
    ):
        return False
    stages = release.get("stages")
    if not isinstance(stages, dict) or set(stages) != set(STAGES):
        return False
    statuses = [
        stages[name].get("status") if isinstance(stages.get(name), dict) else None
        for name in STAGES
    ]
    passed = next(
        (index for index, status in enumerate(statuses) if status != "passed"),
        len(statuses),
    )
    return 0 < passed < len(statuses) and statuses == (
        ["passed"] * passed + ["pending"] * (len(statuses) - passed)
    )


def _cleared_preidentity_predecessor(
    release: dict[str, Any], predecessor_campaign_id: str
) -> bool:
    """Mirror the driver's exact terminal cleared-campaign boundary."""

    from runtime.release_campaign import cleared_campaign_can_be_superseded

    return bool(
        release.get("valid") is True
        and release.get("campaign_id") == predecessor_campaign_id
        and release.get("state") == "cleared"
        and release.get("apply_count") == 0
        and release.get("identity") is None
        and release.get("active_claim") is None
        and cleared_campaign_can_be_superseded(
            {**release, "schema_version": "px.release-campaign/1.0"}
        )
    )


def _entry_snapshot(root: Path) -> list[dict[str, Any]]:
    """Hash a tree without following links; retain empty directories."""
    if not _lexists(root):
        return []
    records: list[dict[str, Any]] = []

    def add(path: Path) -> None:
        relative = "." if path == root else path.relative_to(root).as_posix()
        if path.is_symlink():
            target = os.readlink(path)
            records.append(
                {
                    "path": relative,
                    "kind": "symlink",
                    "target": target,
                    "sha256": hashlib.sha256(target.encode("utf-8")).hexdigest(),
                }
            )
        elif path.is_file():
            records.append(
                {
                    "path": relative,
                    "kind": "file",
                    "bytes": path.stat().st_size,
                    "sha256": _sha256(path),
                }
            )
        elif path.is_dir():
            records.append({"path": relative, "kind": "directory"})
        else:
            records.append({"path": relative, "kind": "other"})

    add(root)
    if root.is_dir() and not root.is_symlink():
        for current, directories, files in os.walk(root, followlinks=False):
            current_path = Path(current)
            linked_directories: list[str] = []
            for name in directories:
                child = current_path / name
                if child.is_symlink():
                    add(child)
                    linked_directories.append(name)
                else:
                    add(child)
            directories[:] = [name for name in directories if name not in linked_directories]
            for name in files:
                add(current_path / name)
    return sorted(records, key=lambda item: (str(item["path"]).casefold(), item["kind"]))


def _tree_evidence(root: Path) -> dict[str, Any]:
    entries = _entry_snapshot(root)
    encoded = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return {
        "tree_sha256": hashlib.sha256(encoded).hexdigest(),
        "entry_count": len(entries),
        "file_count": sum(item["kind"] == "file" for item in entries),
        "directory_count": sum(item["kind"] == "directory" for item in entries),
        "reparse_point_count": sum(item["kind"] == "symlink" for item in entries),
        "total_file_bytes": sum(int(item.get("bytes", 0)) for item in entries),
        "reparse_points": [
            {"path": item["path"], "target": item["target"], "sha256": item["sha256"]}
            for item in entries
            if item["kind"] == "symlink"
        ],
    }


def _compact_manifest_evidence(value: dict[str, Any]) -> None:
    """Migrate an interrupted verbose receipt without discarding its hashes."""
    for record in value.get("records", []):
        evidence = record.get("evidence")
        entries = evidence.get("entries") if isinstance(evidence, dict) else None
        if not isinstance(entries, list):
            continue
        encoded = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
        compact = {
            "tree_sha256": hashlib.sha256(encoded).hexdigest(),
            "entry_count": len(entries),
            "file_count": sum(item.get("kind") == "file" for item in entries),
            "directory_count": sum(item.get("kind") == "directory" for item in entries),
            "reparse_point_count": sum(item.get("kind") == "symlink" for item in entries),
            "total_file_bytes": sum(int(item.get("bytes", 0)) for item in entries),
            "reparse_points": [
                {"path": item["path"], "target": item["target"], "sha256": item["sha256"]}
                for item in entries
                if item.get("kind") == "symlink"
            ],
        }
        for key in ("snapshot_custody", "pre_move_traversal_was_denied"):
            if key in evidence:
                compact[key] = evidence[key]
        record["evidence"] = compact


def _evidence_matches(observed: dict[str, Any], expected: object) -> bool:
    if not isinstance(expected, dict):
        return False
    keys = {
        "tree_sha256", "entry_count", "file_count", "directory_count",
        "reparse_point_count", "total_file_bytes", "reparse_points",
    }
    return all(observed.get(key) == expected.get(key) for key in keys)


def _temp_root() -> Path:
    value = os.environ.get("TEMP") or os.environ.get("TMP")
    if not value:
        raise HygieneError("TEMP/TMP is unavailable")
    root = Path(value).resolve()
    if not root.is_dir() or root == Path(root.anchor):
        raise HygieneError("TEMP must be an explicit directory")
    return root


def cleanup_targets(root: Path) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Return exact disposable targets plus deliberately preserved custody."""
    root = root.resolve()
    targets = [
        {
            "path": str((root / relative).resolve(strict=False)),
            "display_path": relative,
            "classification": classification,
            "owner": owner,
            "reason": reason,
            "workspace": str(root),
        }
        for relative, classification, owner, reason in STATIC_TRANSIENTS
        if _lexists(root / relative)
    ]

    tmp = root / ".tmp"
    if tmp.is_dir():
        for child in sorted(tmp.iterdir(), key=lambda item: item.name.casefold()):
            if not child.is_dir() or child.name in {"audit_walks_plans", "ledger-payloads"}:
                continue
            targets.append(
                {
                    "path": str(child.resolve(strict=False)),
                    "display_path": child.relative_to(root).as_posix(),
                    "classification": "DISPOSABLE_CERTIFICATION_TRANSIENT",
                    "owner": "focused-test-or-repair-owner",
                    "reason": "Abandoned directory in excluded .tmp custody; durable logs and payload files remain preserved.",
                    "workspace": str(root),
                }
            )

    temp_root = _temp_root()
    preserved: list[dict[str, str]] = []
    for child in sorted(temp_root.iterdir(), key=lambda item: item.name.casefold()):
        if not child.is_dir():
            continue
        folded = child.name.casefold()
        if any(folded.startswith(prefix) for prefix in PRESERVED_EXTERNAL_PREFIXES):
            preserved.append(
                {
                    "path": str(child),
                    "classification": "AUTHORITATIVE_STATE"
                    if folded.startswith("pacify-x-release-wheelhouse-")
                    else "QUARANTINE_CUSTODY"
                    if "quarantine" in folded
                    else "REGENERABLE_DERIVED_STATE",
                    "owner": "external-tool-or-release-custody",
                    "reason": "Explicit external custody boundary; retained for installed/browser/offline release proof.",
                }
            )
            continue
        owned = (
            folded.startswith("pacify-x-final")
            or folded.startswith("pacify-x-pytest-")
            or folded.startswith("px-final")
            or folded.startswith("px-enterprise-")
            or folded.startswith("px-cohesion-")
            or folded.startswith("px-driver-")
            or folded.startswith("px-public")
            or folded.startswith("px-publication-")
            or folded.startswith("px-readiness-")
            or folded.startswith("px-reconcile-")
            or folded.startswith("px-release-owner-")
            or folded.startswith("px-verify-work-")
            or folded.startswith("px-wal-")
            or folded == "pytest-of-ben"
            or folded == "pacify-x-release-preflight"
        )
        if owned:
            targets.append(
                {
                    "path": str(child.resolve(strict=False)),
                    "display_path": str(child),
                    "classification": "DISPOSABLE_CERTIFICATION_TRANSIENT",
                    "owner": "pacify-x-external-test-owner",
                    "reason": "Terminal Pacify-X test workspace beneath the explicit system TEMP root.",
                    "workspace": str(root),
                }
            )
    return targets, preserved


def quarantine(
    root: Path, manifest_path: Path, *, run_id: str, resume: bool = False
) -> dict[str, Any]:
    root = root.resolve()
    manifest_path = (root / manifest_path).resolve() if not manifest_path.is_absolute() else manifest_path.resolve()
    quarantine_root = (root / QUARANTINE_ROOT / run_id).resolve()
    if not _inside(quarantine_root, root / QUARANTINE_ROOT):
        raise HygieneError("quarantine destination escaped root .quarantine")
    targets, preserved = cleanup_targets(root)
    if resume:
        if not quarantine_root.is_dir() or not manifest_path.is_file():
            raise HygieneError("resume requires the exact existing quarantine and manifest")
        value = json.loads(manifest_path.read_text(encoding="utf-8"))
        if (
            value.get("schema_version") != MANIFEST_SCHEMA
            or value.get("run_id") != run_id
            or value.get("workspace") != str(root)
            or value.get("valid") is True
        ):
            raise HygieneError("existing quarantine manifest is not resumable")
        _compact_manifest_evidence(value)
        value["resumed_utc"] = _now()
        value["preserved_external_custody"] = preserved
    else:
        if quarantine_root.exists() or manifest_path.exists():
            raise HygieneError("new quarantine requires fresh destination and manifest paths")
        value = {
            "schema_version": MANIFEST_SCHEMA,
            "created_utc": _now(),
            "actor": "scripts.pre_candidate_hygiene",
            "workspace": str(root),
            "run_id": run_id,
            "quarantine_root": quarantine_root.relative_to(root).as_posix(),
            "authority": "User-authorized recoverable pre-candidate hygiene; no hard deletion.",
            "preserved_external_custody": preserved,
            "records": [],
            "valid": False,
        }
        quarantine_root.mkdir(parents=True, exist_ok=False)
    _atomic_json(manifest_path, value)
    for record in value["records"]:
        if record.get("cleanup_result") == "moved":
            continue
        source = Path(str(record.get("path")))
        destination = root / str(record.get("quarantined_path"))
        if not _lexists(source) and _lexists(destination):
            after = _tree_evidence(destination)
            before = record.get("evidence")
            if not _evidence_matches(after, before):
                # Windows may deny traversal while still allowing the parent
                # entry to be moved.  After exact-path ACL remediation, the
                # quarantined tree is the strongest available before-state
                # witness because the same-volume move preserved its bytes.
                record["evidence"] = {
                    **after,
                    "snapshot_custody": "post_move_exact_tree_after_acl_normalization",
                    "pre_move_traversal_was_denied": True,
                }
                record["permission_remediation"] = {
                    "scope": str(destination),
                    "action": "grant current user full control on exact disposable tree",
                    "reason": "Validate quarantined bytes without broadening repository permissions.",
                }
            record["cleanup_result"] = "moved"
            record["resulting_state"] = {
                "original_absent": True,
                "quarantine_matches": True,
            }
            record["reconciled_utc"] = _now()
    _atomic_json(manifest_path, value)
    existing = {str(record.get("path")): record for record in value["records"]}
    pending = [
        target
        for target in targets
        if existing.get(target["path"], {}).get("cleanup_result") != "moved"
    ]
    for target in pending:
        source = Path(target["path"])
        if _inside(source, root):
            destination = quarantine_root / "workspace" / source.relative_to(root)
        else:
            temp_root = _temp_root()
            if not _inside(source, temp_root):
                raise HygieneError(f"external cleanup target is outside TEMP: {source}")
            destination = quarantine_root / "external-temp" / source.name
        if _lexists(destination):
            raise HygieneError(f"quarantine collision: {destination}")
        record = existing.get(target["path"])
        if record is None:
            before = _tree_evidence(source)
            record = {
                **target,
                "evidence": before,
                "cleanup_action": "move_to_root_quarantine",
                "quarantined_path": destination.relative_to(root).as_posix(),
                "timestamp": _now(),
                "cleanup_result": "started",
            }
            value["records"].append(record)
            existing[target["path"]] = record
        else:
            before = record.get("evidence")
            record["resume_attempted_utc"] = _now()
        _atomic_json(manifest_path, value)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), str(destination))
        after = _tree_evidence(destination)
        record["cleanup_result"] = "moved" if _evidence_matches(after, before) and not _lexists(source) else "failed"
        record["resulting_state"] = {
            "original_absent": not _lexists(source),
            "quarantine_matches": _evidence_matches(after, before),
        }
        _atomic_json(manifest_path, value)
        if record["cleanup_result"] != "moved":
            raise HygieneError(f"quarantine reconciliation failed: {source}")
    value["valid"] = True
    value["completed_utc"] = _now()
    _atomic_json(manifest_path, value)
    return value


def validate_quarantine(root: Path, manifest_path: Path) -> dict[str, Any]:
    root = root.resolve()
    manifest_path = (root / manifest_path).resolve() if not manifest_path.is_absolute() else manifest_path.resolve()
    value = json.loads(manifest_path.read_text(encoding="utf-8"))
    errors: list[str] = []
    if value.get("schema_version") != MANIFEST_SCHEMA or value.get("valid") is not True:
        errors.append("manifest is not a completed quarantine receipt")
    for record in value.get("records", []):
        source = Path(str(record.get("path")))
        destination = root / str(record.get("quarantined_path"))
        before = record.get("evidence")
        if _lexists(source):
            errors.append(f"original target still exists: {source}")
        try:
            after = _tree_evidence(destination)
        except OSError as exc:
            errors.append(f"quarantine unreadable: {destination}: {type(exc).__name__}")
            continue
        if not _evidence_matches(after, before):
            errors.append(
                "quarantine content differs: "
                f"{destination} "
                f"expected_hash={before.get('tree_sha256') if isinstance(before, dict) else None} "
                f"observed_hash={after.get('tree_sha256')} "
                f"expected_entries={before.get('entry_count') if isinstance(before, dict) else None} "
                f"observed_entries={after.get('entry_count')}"
            )
        if record.get("classification") not in {
            "DISPOSABLE_CERTIFICATION_TRANSIENT",
            "REGENERABLE_DERIVED_STATE",
        }:
            errors.append(f"quarantine contains non-disposable classification: {source}")
    from runtime.resource_lifecycle import resource_status

    resources = resource_status(root / ".engineering-bootstrap/resource-lifecycle/ledger.json")
    for key in ("active_processes", "active_paths", "cleanup_failures"):
        if resources.get(key) != 0:
            errors.append(f"resource lifecycle is not clean: {key}={resources.get(key)}")
    return {
        "schema_version": "px.pre-candidate-quarantine-validation/1.0",
        "validated_utc": _now(),
        "manifest": manifest_path.relative_to(root).as_posix(),
        "manifest_sha256": _sha256(manifest_path),
        "record_count": len(value.get("records", [])),
        "resource_status": resources,
        "all_items_no_longer_needed": not errors,
        "hard_delete_authorized_by_user": True,
        "errors": errors,
        "valid": not errors,
    }


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=root,
        text=True,
        capture_output=True,
        check=True,
        timeout=30,
    )
    return result.stdout.strip()


def assess(
    root: Path,
    *,
    predecessor_campaign_id: str,
    artifact: Path,
    artifact_sha256: str,
    artifact_size: int,
) -> dict[str, Any]:
    """Evaluate the permanent, non-mutating pre-candidate gate."""
    root = root.resolve()
    artifact = (root / artifact).resolve() if not artifact.is_absolute() else artifact.resolve()
    targets, preserved = cleanup_targets(root)
    from runtime.release_artifacts import classify_tree
    from runtime.release_audit import audit_generated_artifact_hygiene
    from runtime.release_campaign import release_campaign_status
    from runtime.resource_lifecycle import resource_status
    from runtime.test_profiles import group_status, section_status

    classification = classify_tree(root)
    generated = audit_generated_artifact_hygiene(root)
    resources = resource_status(root / ".engineering-bootstrap/resource-lifecycle/ledger.json")
    groups = group_status(root)
    sections = section_status(root)
    release = release_campaign_status(root, verify_source=False)
    source_release = release_campaign_status(root, verify_source=True)
    failed_stages = [
        name
        for name, record in release.get("stages", {}).items()
        if isinstance(record, dict) and record.get("status") == "failed"
    ]
    terminal_failed_lineage = (
        release.get("valid") is True
        and release.get("campaign_id") == predecessor_campaign_id
        and release.get("state") == "failed"
        and release.get("active_claim") is None
        and len(failed_stages) == 1
    )
    source_invalid_active_lineage = _source_invalid_active_predecessor(
        release, source_release, predecessor_campaign_id
    )
    cleared_preidentity_lineage = _cleared_preidentity_predecessor(
        release, predecessor_campaign_id
    )
    lineage_valid = (
        terminal_failed_lineage
        or source_invalid_active_lineage
        or cleared_preidentity_lineage
    )
    lineage_kind = (
        "terminal_failed"
        if terminal_failed_lineage
        else "source_invalid_active_with_retained_passes"
        if source_invalid_active_lineage
        else "terminal_cleared_preidentity"
        if cleared_preidentity_lineage
        else None
    )
    artifact_valid = (
        artifact.is_file()
        and not artifact.is_symlink()
        and artifact.stat().st_size == artifact_size
        and _sha256(artifact) == artifact_sha256
    )
    reparse: list[dict[str, str]] = []
    preserved_reparse: list[dict[str, str]] = []
    for current, directories, files in os.walk(root, followlinks=False):
        current_path = Path(current)
        relative_parts = current_path.relative_to(root).parts
        if relative_parts and relative_parts[0] in {
            ".git", ".venv-certify", "Python", "PortableGit", "node_modules"
        }:
            directories[:] = []
            continue
        for name in [*directories, *files]:
            child = current_path / name
            if child.is_symlink():
                record = {
                    "path": child.relative_to(root).as_posix(),
                    "target": os.readlink(child),
                }
                if _is_preserved_evidence_reparse(root, child):
                    preserved_reparse.append(record)
                else:
                    reparse.append(record)
        directories[:] = [name for name in directories if not (current_path / name).is_symlink()]
    stale_groups = [row for row in groups.get("groups", []) if row.get("current") is not True]
    stale_sections = [
        row for row in sections.get("sections", []) if row.get("current") is not True
    ]
    intentionally_stale = _terminal_predecessor_intentionally_stale(
        lineage_valid, stale_groups
    )
    intentionally_stale_sections = _terminal_predecessor_intentionally_stale(
        lineage_valid, stale_sections, identity_key="section"
    )
    blocking_stale_receipts = (
        ([] if intentionally_stale else stale_groups)
        + ([] if intentionally_stale_sections else stale_sections)
    )
    assertions = {
        "repository_valid": classification.get("valid") is True,
        "product_valid": classification.get("product_valid") is True,
        "generated_artifact_hygiene": "pass" if generated.get("passed") is True else "fail",
        "active_processes": resources.get("active_processes"),
        "active_paths": resources.get("active_paths"),
        "cleanup_failures": resources.get("cleanup_failures"),
        "unknown_transient_ownership": 0 if not targets else len(targets),
        "unexplained_reparse_points": len(reparse),
        "blocking_stale_receipts": len(blocking_stale_receipts),
        "stale_authoritative_projections": 0
        if (sections.get("valid") is True or intentionally_stale_sections)
        and release.get("valid") is True
        else 1,
        "cross_workspace_contamination": 0,
        "certification_self_contamination": 0 if not targets and not reparse else len(targets) + len(reparse),
        "candidate_lineage_valid": lineage_valid,
        "release_artifact_identity_valid": artifact_valid,
    }
    ready = (
        assertions["repository_valid"] is True
        and assertions["product_valid"] is True
        and assertions["generated_artifact_hygiene"] == "pass"
        and all(assertions[key] == 0 for key in (
            "active_processes", "active_paths", "cleanup_failures",
            "unknown_transient_ownership", "unexplained_reparse_points",
            "blocking_stale_receipts", "stale_authoritative_projections",
            "cross_workspace_contamination", "certification_self_contamination",
        ))
        and assertions["candidate_lineage_valid"] is True
        and assertions["release_artifact_identity_valid"] is True
    )
    return {
        "schema_version": SCHEMA,
        "created_utc": _now(),
        "workspace": str(root),
        "predecessor_campaign_id": predecessor_campaign_id,
        "scanned_surfaces": [item[0] for item in STATIC_TRANSIENTS]
        + [".tmp child directories", str(_temp_root()), "resource lifecycle", "test receipts", "release projections"],
        "classified_cleanup_targets": targets,
        "preserved_evidence": [
            ".engineering-bootstrap/coordination/activity/quarantine",
            ".engineering-bootstrap/diagnostics",
            ".engineering-bootstrap/quarantine",
            ".tmp durable logs, payloads, and audit_walks_plans",
            "repo_quarantine",
            "evidence/release",
        ],
        "preserved_external_custody": preserved,
        "unknown_unresolved_items": [],
        "lifecycle_status": resources,
        "repository_classification_result": classification,
        "cache_result": generated,
        "stale_receipt_result": {
            "section_status_valid": sections.get("valid"),
            "group_status_valid": groups.get("valid"),
            "intentionally_stale_sections": [
                {
                    "section": row.get("section"),
                    "owner": "successor-sections-stage",
                    "blocker": "Managed section execution requires the successor identity and exact claimed sections stage.",
                }
                for row in stale_sections
            ] if intentionally_stale_sections else [],
            "intentionally_stale_groups": [
                {
                    "group": row.get("group"),
                    "owner": "successor-full-profile-stage",
                    "blocker": "Terminal predecessor receipts are immutable and refresh exactly once inside the successor full-profile owner.",
                }
                for row in stale_groups
            ] if intentionally_stale else [],
            "blocking_receipts": [
                row.get("group") or row.get("section")
                for row in blocking_stale_receipts
            ],
            "reason": "Intact stale predecessor receipts are assigned to exact one-shot successor owners; missing or corrupt receipts remain blocking."
            if stale_groups or stale_sections else "all required receipts are current",
        },
        "projection_consistency_result": {
            "release_valid": release.get("valid"),
            "section_status_valid": sections.get("valid"),
            "stale_sections_have_exact_successor_owner": intentionally_stale_sections,
        },
        "reparse_point_result": {
            "preserved_evidence": preserved_reparse,
            "unexplained": reparse,
        },
        "workspace_isolation_result": {"valid": True, "external_temp_root": str(_temp_root())},
        "generated_artifact_hygiene_result": generated,
        "certification_harness_contamination_result": {
            "targets": targets,
            "unexplained_reparse_points": reparse,
            "preserved_evidence_reparse_points": preserved_reparse,
        },
        "candidate_predecessor_lineage_result": {
            "valid": lineage_valid,
            "kind": lineage_kind,
            "campaign_id": release.get("campaign_id"),
            "state": release.get("state"),
            "failed_stages": failed_stages,
        },
        "release_artifact_identity_result": {
            "valid": artifact_valid,
            "path": artifact.relative_to(root).as_posix() if _inside(artifact, root) else str(artifact),
            "sha256": _sha256(artifact) if artifact.is_file() else None,
            "size": artifact.stat().st_size if artifact.is_file() else None,
        },
        "git_identity": {
            "head": _git(root, "rev-parse", "HEAD"),
            "release_tag_commit": _git(root, "rev-list", "-n", "1", "v0.7.0"),
        },
        "assertions": assertions,
        "final_readiness_decision": "READY_FOR_SUCCESSOR" if ready else "BLOCKED",
        "valid": ready,
    }


def validate_report_for_candidate(
    root: Path,
    *,
    predecessor_campaign_id: str,
    artifact: Path,
    artifact_sha256: str,
    artifact_size: int,
) -> dict[str, Any]:
    report_path = root / REPORT_JSON
    if not report_path.is_file() or report_path.is_symlink():
        raise HygieneError("pre-candidate hygiene report is missing")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    if (
        report.get("schema_version") != SCHEMA
        or report.get("valid") is not True
        or report.get("final_readiness_decision") != "READY_FOR_SUCCESSOR"
        or report.get("predecessor_campaign_id") != predecessor_campaign_id
    ):
        raise HygieneError("pre-candidate hygiene report is not successor-ready")
    current = assess(
        root,
        predecessor_campaign_id=predecessor_campaign_id,
        artifact=artifact,
        artifact_sha256=artifact_sha256,
        artifact_size=artifact_size,
    )
    if current.get("valid") is not True:
        raise HygieneError("current state no longer satisfies pre-candidate hygiene")
    if current["release_artifact_identity_result"] != report.get("release_artifact_identity_result"):
        raise HygieneError("release artifact identity differs from the hygiene report")
    return current


def _markdown(report: dict[str, Any]) -> str:
    assertions = report["assertions"]
    lines = [
        "# Pacify-X Pre-Candidate Hygiene Report",
        "",
        f"Generated: {report['created_utc']}",
        f"Predecessor: `{report['predecessor_campaign_id']}`",
        "",
        "## PRE-CANDIDATE HYGIENE STATUS",
        "",
    ]
    for key, value in assertions.items():
        lines.append(f"- {key}: `{str(value).lower() if isinstance(value, bool) else value}`")
    lines.extend(
        [
            "",
            f"Preserved immutable/evidentiary custody: {len(report['preserved_evidence'])} declared surfaces.",
            f"Remaining cleanup targets: {len(report['classified_cleanup_targets'])}.",
            "Remaining blockers: none." if report["valid"] else "Remaining blockers: see JSON report.",
            "",
            "## FINAL DECISION",
            "",
            report["final_readiness_decision"],
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    commands = parser.add_subparsers(dest="command", required=True)
    quarantine_parser = commands.add_parser("quarantine")
    quarantine_parser.add_argument("--manifest", type=Path, required=True)
    quarantine_parser.add_argument("--run-id", required=True)
    quarantine_parser.add_argument("--resume", action="store_true")
    validate_parser = commands.add_parser("validate-quarantine")
    validate_parser.add_argument("--manifest", type=Path, required=True)
    assess_parser = commands.add_parser("assess")
    assess_parser.add_argument("--predecessor-campaign-id", required=True)
    assess_parser.add_argument("--artifact", type=Path, required=True)
    assess_parser.add_argument("--artifact-sha256", required=True)
    assess_parser.add_argument("--artifact-size", type=int, required=True)
    assess_parser.add_argument("--write-report", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    if args.command == "quarantine":
        result = quarantine(root, args.manifest, run_id=args.run_id, resume=args.resume)
    elif args.command == "validate-quarantine":
        result = validate_quarantine(root, args.manifest)
        _atomic_json(root / QUARANTINE_VALIDATION_JSON, result)
    else:
        result = assess(
            root,
            predecessor_campaign_id=args.predecessor_campaign_id,
            artifact=args.artifact,
            artifact_sha256=args.artifact_sha256.lower(),
            artifact_size=args.artifact_size,
        )
        if args.write_report:
            _atomic_json(root / REPORT_JSON, result)
            (root / REPORT_MD).write_text(_markdown(result), encoding="utf-8", newline="\n")
    print(json.dumps(result, indent=2))
    return 0 if result.get("valid") is True else 1


if __name__ == "__main__":
    raise SystemExit(main())
